# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtc', '0002_suggestionforreview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TidUniprotGenenames',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot_id', models.TextField(blank=True, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tid_uniprot_genenames',
                'managed': False,
            },
        ),
    ]
