# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtc', '0003_tiduniprotgenenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(blank=True, max_length=30, null=True)),
                ('term_name', models.CharField(blank=True, max_length=4000, null=True)),
                ('term_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'start_search',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='suggestionforreview',
            options={'managed': False},
        ),
    ]
